<%@ Page Language="C#" AutoEventWireup="true" MasterPageFile="~/Site.Master" CodeBehind="EditFormTable.aspx.cs" Inherits="CustServForm.CustComplaints.EditFormTable" %>

<asp:Content ID="BodyContent" ContentPlaceHolderID="MainContent" runat="server">

<link rel="stylesheet" href="styles.css" type="text/css" />
<asp:XmlDataSource ID="locData" runat="server" DataFile="~/Locations.xml"></asp:XmlDataSource>

<!-- Navbar -->
<ul>
    <li><a href="WebComplaint.aspx">Website</a></li>
    <li><a href="AppComplaint.aspx">App</a></li>
    <li><a href="KioskGate.aspx">Gate/Kiosk</a></li>
    <li><a href="POSComplaint.aspx">POS</a></li>
    <li><a href="Valet.aspx">Valet App</a></li>
    <li style="float: right"><a href="EditForm.aspx">Add to Form</a></li>
    <li style="float: right"><a class="active" href="EditFormTable.aspx">Edit Form</a></li>
</ul>
<!-- Main form content -->
<asp:UpdatePanel runat="server" ID="mobilePanel" UpdateMode="Conditional">
<ContentTemplate>
<div class="main-content">
<asp:Table runat="server">
    <%-- Add Location Menu --%>
    <asp:TableRow>
        <asp:TableCell>
            <asp:GridView runat="server" ID="locTable" AutoGenerateColumns="false" AutoGenerateDeleteButton="true" AutoGenerateEditButton="true" 
                OnRowDeleting="DeleteLocation" OnRowEditing="EditLocation" OnRowUpdating="UpdateLocation" OnRowCancelingEdit="CancelEditLocation">
                
            </asp:GridView>
        </asp:TableCell>
    </asp:TableRow>
</asp:Table>
</div>
</ContentTemplate>
</asp:UpdatePanel>
</asp:Content>